"""Document-intelligence substrate: immutable assets, parsed pages, evidence."""

from mastervault.document_intelligence.docling_adapter import (
    DoclingParser,
    doctor_docling,
)
from mastervault.document_intelligence.grounding import (
    evidence_errors,
    resolve_evidence,
    validate_resolved_evidence,
)
from mastervault.document_intelligence.models import (
    DOCUMENT_SCHEMA_VERSION,
    LATEST_DOCUMENT_SCHEMA_VERSION,
    DocumentBlock,
    DocumentBlockType,
    DocumentBlockV2,
    DocumentResourceLimits,
    DocumentSectionV2,
    DocumentTableV2,
    EvidenceRef,
    NormalizedBBox,
    ParsedDocument,
    ParsedDocumentAny,
    ParsedDocumentRef,
    ParsedDocumentV2,
    ParsedPage,
    ParsedPageV2,
    ParseWarning,
    SourceAssetRef,
    StructuralEvidenceRef,
    TableCellV2,
    TableRowV2,
)
from mastervault.document_intelligence.parser import (
    DocumentParser,
    PdfSource,
    PypdfParser,
    load_pdf_source,
    make_document_parser,
    parse_pdf,
)
from mastervault.document_intelligence.renderer import render_document_markdown
from mastervault.document_intelligence.store import (
    load_parsed_document,
    parsed_document_bytes,
    parsed_document_sha256,
    store_parsed_document,
    store_source_asset,
    verify_source_asset,
)

__all__ = [
    "DOCUMENT_SCHEMA_VERSION",
    "DocumentBlock",
    "DocumentBlockType",
    "DocumentBlockV2",
    "DocumentParser",
    "DocumentResourceLimits",
    "DocumentSectionV2",
    "DocumentTableV2",
    "DoclingParser",
    "EvidenceRef",
    "LATEST_DOCUMENT_SCHEMA_VERSION",
    "NormalizedBBox",
    "ParsedDocument",
    "ParsedDocumentAny",
    "ParsedDocumentRef",
    "ParsedDocumentV2",
    "ParsedPage",
    "ParsedPageV2",
    "ParseWarning",
    "PdfSource",
    "PypdfParser",
    "SourceAssetRef",
    "StructuralEvidenceRef",
    "TableCellV2",
    "TableRowV2",
    "doctor_docling",
    "evidence_errors",
    "load_parsed_document",
    "load_pdf_source",
    "make_document_parser",
    "parse_pdf",
    "parsed_document_bytes",
    "parsed_document_sha256",
    "resolve_evidence",
    "render_document_markdown",
    "store_parsed_document",
    "store_source_asset",
    "validate_resolved_evidence",
    "verify_source_asset",
]
